name: DEFT
channels:
  - pytorch
  - conda-forge
  - anaconda
  - numba
  - defaults
dependencies:
  - bzip2=1.0.8=h7b6447c_0
  - cairo=1.14.12=h8948797_3
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.14=h23475e2_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - jasper=2.0.14=h07fcdf6_1
  - joblib=0.16.0=py_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - pcre=8.44=he6710b0_0
  - pixman=0.40.0=h7b6447c_0
  - py-opencv=3.4.2=py36hb342d67_1
  - scipy=1.1.0=py36hfa4b5c9_1
  - six=1.15.0=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - cycler=0.10.0=py_2
  - cython=0.29.21=py36h831f99a_0
  - kiwisolver=1.2.0=py36hdb11119_0
  - matplotlib-base=3.3.1=py36h5ffbc53_1
  - progress=1.5=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - quaternion=2020.5.19.15.27.24=py36h785e9b2_0
  - tornado=6.0.4=py36h8c4c3a4_1
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py36_0
  - cffi=1.14.2=py36he30daa8_0
  - cudatoolkit=10.0.130=0
  - freetype=2.10.2=h5ab3b9f_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=he6710b0_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.1.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.0=py36hfd86e86_0
  - numpy=1.19.1=py36hbc911f0_0
  - numpy-base=1.19.1=py36hfa32c7d_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=h7b6447c_0
  - pillow=7.2.0=py36hb39fc2d_0
  - pip=20.2.2=py36_0
  - pycparser=2.20=py_2
  - python=3.6.10=h7579374_2
  - readline=8.0=h7b6447c_0
  - setuptools=49.6.0=py36_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - llvmlite=0.34.0=py36hf484d3e_0
  - numba=0.51.1=np1.11py3.6h04863e7_gc5f8505fb_0
  - cuda100=1.0=0
  - pytorch=1.2.0=py3.6_cuda10.0.130_cudnn7.6.2_0
  - torchvision=0.4.0=py36_cu100
prefix: /s/red/a/nobackup/vision/chaabane/tracker/DEFT/anaconda/anaconda3/envs/DEFT

